name: berlinfashionfilmfestival
favicon: null
layout_spectrum: 0.7116079838015139
typography_spectrum: 0.13904840336181223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0067ad'
    - '#f20088'
    - '#000000'
    - '#65a1cd'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
