name: berlinfashionfilmfestival
favicon: null
layout_spectrum: 0.7116079838015139
typography_spectrum: 0.13904840336181223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8413633774034679
  lightness: 0.10716610844247043
  saturation: 0.4145052977837622
  rhythmicContrast: 0.27984275575727224
purpose: []
