name: fashionfilmconsultant
favicon: null
layout_spectrum: 0.7116079838015139
typography_spectrum: 0.13904840336181223
title: fashionfilmconsultantniccolomontanari
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#58677b'
    - '#521417'
    - '#343b49'
    - '#9e9b93'
    - '#81311d'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
